### ISSUE TITLE
Change verbiage to be more generically about NPCs?

### ISSUE THREAD

**Issue by wlonk** [wlonk/maskbook#38]
Or at least tell people these don't have to be villains-as-such?

**Comment by WeirdGamer** [comment]
Would it be possible to have one section for NPCs and another for villains?

**Comment by wlonk** [comment]
I think that the distinction between them is not that sharp; what I'm inclined to do is leverage the tagging system to support this with a bit more flexibility.

**Comment by WeirdGamer** [comment]
True, I guess the only real difference is they don't have conditions, so when creating non-villains that section could just be left blank.

**Comment by wlonk** [comment]
I would assume that even non-villains would have Conditions, when it comes to it; I take the "Villain" creation rules to really be "NPCs who you might fight".

**Comment by WeirdGamer** [comment]
From the rules:
NPC CONDITIONS
For the most part, NPCs don’t have that many conditions to mark. The only
real way they mark conditions is if a PC directly engaged them, and only
NPCs with real abilities ever count as threats for that move to trigger—and
they’re probably villains. (More on villains in a moment.) So don’t worry about
tracking conditions for anyone except the villains—everybody else simply
reacts according to the fiction.
------------------------
But really it's a minor point. I'm just nitpicking at this point.

**Comment by wlonk** [comment]
Yeah, that's exactly the text I was thinking of when I wrote the above. If you really want to make a character with zero conditions, of course you can do that, too.

**Comment by WeirdGamer** [comment]
Yeah, it does also note in the book that villains are NPCs you might fight. Like a said just a minor quibble on my part. keep up the great work!
